version: "3.3"
services:
  db:
    image: postgres:12
    volumes:
      - /var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  backend:
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: backend.dockerfile
  
  nuxt:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    volumes:
      - ./frontend/app:/app
    restart: always
    ports:
      - "3000:3000"
    command: npm run dev
    # command: /bin/sh -c "tail -f /dev/null"

