# Generated by Django 3.2.4 on 2021-06-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'class'},
        ),
        migrations.RenameField(
            model_name='school',
            old_name='address',
            new_name='school_address',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='name',
            new_name='school_name',
        ),
    ]
