# Generated by Django 3.2.4 on 2021-06-10 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0002_auto_20210608_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='principal_email',
            field=models.EmailField(default='siema', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
