# Generated by Django 3.2.4 on 2021-06-24 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20210624_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='school',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='school_lessons', to='school.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='school_class',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='class_lessons', to='school.schoolclass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='school.schoolclass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='school_subjects', to='school.school'),
            preserve_default=False,
        ),
    ]
