# Generated by Django 3.2.4 on 2021-06-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20210624_2105'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('school', 'yearbook', 'class_label')},
        ),
    ]
