# Generated by Django 3.2.5 on 2021-07-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_schoolclass_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'subject_name')},
        ),
    ]
